concord-consortium/slate-editor

- src/editor-toolbar/editor-toolbar.stories.js
- src/editor-toolbar/editor-toolbar.tsx
- src/editor-toolbar/toolbar-button.tsx
- src/slate-container/slate-container.stories.js
Storybook examples use CODAP colors because I was playing around with combinations to see what might work for CODAP.
Note that while fill color has to be specified this way because it can't be set from CSS, we could eliminate the props support for background-color and rely on CSS for that, but it seemed simpler to let clients specify all the colors in one place.
> Support setting fill and background colors of toolbar buttons

- src/plugins/color-plugin.tsx
Previously, once a block of text had a color mark there was no way to clear it. Since black is the default text color, if the user selects black we simply clear the color mark, which unhighlights the color button on the toolbar.
> Selecting black clears the color mark

- src/slate-toolbar/slate-toolbar.stories.js
- src/slate-toolbar/slate-toolbar.tsx
When an ordered list of toolbar buttons is passed to the slate toolbar, filter out buttons that are not in the list and do not display them in the toolbar (instead of adding them to the end of the list).
> filter and remove buttons not in ordered list in slate toolbar

- src/slate-editor/serialization.ts
- src/slate-editor/slate-serialization.stories.js
- src/slate-editor/slate-serialization.stories.scss
The new storybook example shows the serialized contents of the selection dynamically in the same way that the serialization example shows the serialized contents of the entire Slate value, which is useful for understanding how selection is handled and can be queried.
> Add `serializeSelection()`; add storybook example showing current selection

- src/index.tsx
- src/plugins/core-marks-plugin.tsx
- src/serialization/html-serializer.test.tsx
- src/serialization/serialization.stories.js
- src/serialization/serialization.ts
- src/slate-editor/slate-editor.tsx
- Fix behavior of marks imported via HTML
- Pass a raw editor value to onContentChange() rather than a serialized value; client can choose serialization model
> Fix html serialization

- src/plugins/image-plugin.tsx
- src/plugins/on-load-plugin.tsx
- src/slate-editor/slate-editor.tsx
For the question-interactives, the size of the container `<div>` auto-sizes to fit the size of the content. This works fine for plain/rich text, because every change to the model results in an `onValueChange()` callback, at which point the client can measure the size of the content and react accordingly. Images don't work in this model, however, because `<img>` tags appear in the content before their image is actually loaded, and when the image does actually load it doesn't trigger an `onValueChange()` callback. Therefore, we add a new `onLoad()` callback which is triggered whenever a resource loads outside the context of a regular model change. Currently only `<img>` tags use it, but if we encounter any other nodes whose size can change asynchronously from model changes, they can make …
> Add onLoad callback

- src/editor-toolbar/editor-toolbar.stories.js
- src/editor-toolbar/editor-toolbar.tsx
- src/editor-toolbar/toolbar-button.tsx
- src/index.tsx
- src/slate-container/slate-container.stories.js
- src/slate-toolbar/slate-dialog.stories.js
- src/slate-toolbar/slate-toolbar.tsx
Allow client to specify dialog `themeColor` rather than assuming it's the toolbar background color.
Provides means to fix `question-interactives` authoring bug in which toolbar background color is white, resulting in white-on-white text.
> Allow client to specify dialog `themeColor`

- .storybook/webpack.config.js
- jest.config.js
- package-lock.json
- package.json
- rollup.config.js
Primarily includes several IME fixes to enable Chinese/Japanese/etc. input. See [[#173260782]](https://www.pivotaltracker.com/story/show/173260782) for details.
See [@cc/slate #1](https://github.com/concord-consortium/slate/pull/1) and [@cc/slate #2](https://github.com/concord-consortium/slate/pull/2) for details of the underlying fixes.
Most of the changes in this PR relate to aliasing `slate-react` to `@concord-consortium/slate-react` so that client code doesn't need to change.
> Use `@concord-consortium/slate-react` instead of `slate-react`

- package-lock.json
- package.json
- src/editor-toolbar/editor-toolbar.tsx
- src/editor-toolbar/toolbar-button.tsx
Calls `setUserActionPerformed()` on toolbar clicks, which triggers auto-scroll to the selection on the next render.
> Auto-scroll to selection after toolbar invocation

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/plugins/image-plugin.scss
- src/plugins/image-plugin.tsx
- src/slate-editor/slate-editor.test.tsx
- src/slate-editor/slate-editor.tsx
- src/slate-toolbar/modal-dialog.scss
- src/slate-toolbar/modal-dialog.tsx
- src/slate-toolbar/slate-toolbar.tsx
- normalize CSS class names
- flesh out ReadMe including documentation of serialization format
@mklewandowski On the CSS class names, I was thinking about the fact that we're still supporting TinyMCE class names even as we move away from TinyMCE, so we should use class names that will stand the test of time, even if we end up switching to another editor at some point. Now seemed like as good a time as any to normalize them.
> Release 0.5.0

- src/plugins/core-blocks-plugin.tsx
- src/serialization/serialization.stories.tsx
[[#173991240]](https://www.pivotaltracker.com/story/show/173991240) [[#173991084]](https://www.pivotaltracker.com/story/show/173991084)
When importing HTML, we track the tag that was originally imported because in some cases it can be used to re-export the HTML with higher fidelity. For instance, there are some block-level tags that occur in LARA content but that are not explicitly supported by `slate-editor` (e.g. `<fieldset>`). For these blocks, we convert them to a generic `<div>` internally but we also remember the imported tag. On export then, we can write out the original tag, thus preserving the fidelity of the original import. Much of the HTML import/export code was tested by importing and then immediately exporting HTML content and verifying that the fidelity of the original …
> Fix bugs editing some content imported as HTML

- CHANGELOG.md
- package-lock.json
- package.json
- Support legacy `line` block type (synonym for `paragraph`)
> Release 0.7.1

- src/serialization/serialization.stories.tsx
No library changes; just a new example in storybook (which functions as a CLUE authoring environment).
> Add CLUE text tile export story

- package-lock.json
- package.json
- src/plugins/image-plugin.tsx
- src/plugins/link-plugin.tsx
- src/slate-toolbar/modal-dialog.tsx
- src/slate-toolbar/slate-toolbar.tsx
use it to validate user-entered urls for images and links in dialogs
This was suggested by a comment of @lbondaryk's.
Note that our dialog implementation now has two separate notions of validation, one that occurs in `onChange` and one that occurs when the ok button is clicked. There may be a way to unify them at some point but I don't think that day is today.
> Support validation of dialog contents; validate user-entered urls

- src/index.tsx
- src/serialization/html-serializer.test.tsx
- src/serialization/html-serializer.tsx
- src/serialization/html-utils.test.ts
- src/serialization/html-utils.ts
- src/serialization/legacy-serialization.test.ts
- src/serialization/legacy-serialization.ts
- src/serialization/serialization.ts
The symptom was a console error from React about an invalid `classNamename` property. I suspect the problem began with an import of invalid hand-coded HTML which looked something like `<ul><li className="foo">bar</li></ul>` which then introduced the `className` property into the system after which it was copied around to several other places. The fix here is to strip it out or convert it to `class` on import/export depending on circumstances.
Also adds some additional unit tests.
> Handle/ignore `className` property which confuses React

- CHANGELOG.md
- package-lock.json
- package.json
- Convert/strip `className` property on import/export
- Update dependencies
> Release 0.7.2

- package-lock.json
- package.json
- src/common/slate-types.ts
- src/plugins/image-plugin.tsx
- src/serialization/html-serializer.test.tsx
Makes use of [@concord-consortium/slate #5](https://github.com/concord-consortium/slate/pull/5) to enable cut/copy/paste of image-only selections.
> Support clipboard operations on image-only selections

- .eslintrc.js
- .gitignore
- .vscode/settings.json
- package.json
- src/common/slate-types.ts
- src/index.tsx
- src/plugin-examples/icon-variable.tsx
- src/plugin-examples/plugin-examples.stories.tsx
- src/plugin-examples/variable-plugin.scss
- src/plugin-examples/variable-plugin.tsx
- src/slate-container/slate-container.stories.tsx
- src/slate-editor/slate-editor.test.tsx
- src/slate-editor/slate-utils.ts
- src/slate-toolbar/slate-toolbar.stories.tsx
- src/slate-toolbar/slate-toolbar.tsx
This is an updated implementation of the `variable` plugin that no longer requires intrusive changes into the core components and therefore is mergeable as an example of a non-trivial plugin that can be built entirely in userland. A few changes were made to the core `slate-editor` code to support such plugins:
1. Client code can extend the `EFormat` codes by adding their own strings.
2. The `SlateToolbar` component now accepts a `transform` function which can modify the set of default buttons. Previously, there was a mechanism for ordering and filtering the set of default buttons but there was no way to add new buttons and only limited facility for changing the existing buttons. All of this can now be accomplished with the `transform` function. Previous examples which demonstrated the …
> Refactored `variable` plugin

- package-lock.json
- package.json
- src/index.tsx
this also sets the version 0.8.0-beta.2
The changes here are used by this CLUE PR: https://github.com/concord-consortium/collaborative-learning/pull/1257
> export more stuff to support external plugins

- package-lock.json
- package.json
- src/common/slate-types.ts
- src/serialization/html-serializer.test.tsx
- src/serialization/html-serializer.tsx
- src/serialization/serialization.stories.tsx
Some CLUE curriculum files include improperly formatted HTML, in that some text is not wrapped in `<p>` or other block tags. These were being imported into slate as top level text nodes, which are not allowed and caused errors. This fix checks all top level text nodes when importing HTML, removes those with just whitespace, and wraps those with actual content in paragraph nodes.
> Wrap free text nodes when importing HTML

- CHANGELOG.md
- package-lock.json
- package.json
- src/common/custom-types.ts
- src/index.tsx
- Export `isCustomElement()` function
- Fix bug in `ReactEditor.focus()` by downgrading to `slate-react` 0.98.4
> chore: release 0.10.1

- .travis.yml
The old Travis deploy system no longer works, so we simply comment out the deploy steps so the CI build completes successfully as long as the code builds.
> chore: fix .travis.yml by eliminating deploy
